import { Chain } from './types';

export const CHAINS: Record<string, Chain> = {
  ethereum: {
    id: 1,
    name: 'Ethereum',
    shortName: 'ETH',
    rpcUrl: `https://eth-mainnet.g.alchemy.com/v2/${process.env.NEXT_PUBLIC_ALCHEMY_API_KEY || 'V9A0m8eB58qyWJpajjs6Y'}`,
    explorerUrl: 'https://etherscan.io',
    nativeCurrency: {
      name: 'Ethereum',
      symbol: 'ETH',
      decimals: 18,
    },
    color: '#627EEA',
    icon: 'Ξ',
    logoUrl: '/crypto-eth.png',
  },
  polygon: {
    id: 137,
    name: 'Polygon',
    shortName: 'MATIC',
    rpcUrl: 'https://polygon-rpc.com',
    explorerUrl: 'https://polygonscan.com',
    nativeCurrency: {
      name: 'Polygon',
      symbol: 'MATIC',
      decimals: 18,
    },
    color: '#8247E5',
    icon: '⬡',
    logoUrl: '/crypto-polygon.png',
  },
  arbitrum: {
    id: 42161,
    name: 'Arbitrum',
    shortName: 'ARB',
    rpcUrl: 'https://arb1.arbitrum.io/rpc',
    explorerUrl: 'https://arbiscan.io',
    nativeCurrency: {
      name: 'Ethereum',
      symbol: 'ETH',
      decimals: 18,
    },
    color: '#28A0F0',
    icon: '◆',
    logoUrl: '/crypto-arbitrum.png',
  },
  base: {
    id: 8453,
    name: 'Base',
    shortName: 'BASE',
    rpcUrl: 'https://mainnet.base.org',
    explorerUrl: 'https://basescan.org',
    nativeCurrency: {
      name: 'Ethereum',
      symbol: 'ETH',
      decimals: 18,
    },
    color: '#0052FF',
    icon: '🔵',
    logoUrl: '/crypto-base.png',
  },
  sepolia: {
    id: 11155111,
    name: 'Sepolia Testnet',
    shortName: 'SEP',
    rpcUrl: 'https://ethereum-sepolia-rpc.publicnode.com',
    explorerUrl: 'https://sepolia.etherscan.io',
    nativeCurrency: {
      name: 'Ethereum',
      symbol: 'ETH',
      decimals: 18,
    },
    color: '#627EEA',
    icon: 'Ξ',
    logoUrl: '/crypto-eth.png',
    isTestnet: true,
  },
  bsc: {
    id: 56,
    name: 'BNB Smart Chain',
    shortName: 'BSC',
    rpcUrl: 'https://bsc-dataseed.binance.org',
    explorerUrl: 'https://bscscan.com',
    nativeCurrency: {
      name: 'BNB',
      symbol: 'BNB',
      decimals: 18,
    },
    color: '#F3BA2F',
    icon: '💎',
    logoUrl: '/crypto-bnb.png',
  },
  bscTestnet: {
    id: 97,
    name: 'BSC Testnet',
    shortName: 'BSC-T',
    rpcUrl: 'https://data-seed-prebsc-1-s1.binance.org:8545',
    explorerUrl: 'https://testnet.bscscan.com',
    nativeCurrency: {
      name: 'BNB',
      symbol: 'tBNB',
      decimals: 18,
    },
    color: '#F3BA2F',
    icon: '🧪',
    logoUrl: '/crypto-bnb.png',
    isTestnet: true,
  },
  solana: {
    id: 101,
    name: 'Solana',
    shortName: 'SOL',
    rpcUrl: `https://solana-mainnet.g.alchemy.com/v2/${process.env.NEXT_PUBLIC_ALCHEMY_API_KEY || 'demo'}`, // ✅ More reliable RPC
    explorerUrl: 'https://explorer.solana.com',
    nativeCurrency: {
      name: 'Solana',
      symbol: 'SOL',
      decimals: 9,
    },
    color: '#9945FF',
    icon: '◎',
    logoUrl: '/crypto-solana.png',
  },
  optimism: {
    id: 10,
    name: 'Optimism',
    shortName: 'OP',
    rpcUrl: 'https://mainnet.optimism.io',
    explorerUrl: 'https://optimistic.etherscan.io',
    nativeCurrency: {
      name: 'Ethereum',
      symbol: 'ETH',
      decimals: 18,
    },
    color: '#FF0420',
    icon: '🔴',
    logoUrl: '/crypto-optimism.png',
  },
  avalanche: {
    id: 43114,
    name: 'Avalanche',
    shortName: 'AVAX',
    rpcUrl: 'https://api.avax.network/ext/bc/C/rpc',
    explorerUrl: 'https://snowtrace.io',
    nativeCurrency: {
      name: 'Avalanche',
      symbol: 'AVAX',
      decimals: 18,
    },
    color: '#E84142',
    icon: '🔺',
    logoUrl: '/crypto-avalanche.png',
  },
  fantom: {
    id: 250,
    name: 'Fantom',
    shortName: 'FTM',
    rpcUrl: 'https://rpc.ftm.tools',
    explorerUrl: 'https://ftmscan.com',
    nativeCurrency: {
      name: 'Fantom',
      symbol: 'FTM',
      decimals: 18,
    },
    color: '#1969FF',
    icon: '👻',
    logoUrl: '/crypto-fantom.png',
  },
  cronos: {
    id: 25,
    name: 'Cronos',
    shortName: 'CRO',
    rpcUrl: 'https://evm.cronos.org',
    explorerUrl: 'https://cronoscan.com',
    nativeCurrency: {
      name: 'Cronos',
      symbol: 'CRO',
      decimals: 18,
    },
    color: '#002D74',
    icon: '💠',
    logoUrl: '/crypto-cronos.png',
  },
  zksync: {
    id: 324,
    name: 'zkSync Era',
    shortName: 'zkSync',
    rpcUrl: 'https://mainnet.era.zksync.io',
    explorerUrl: 'https://explorer.zksync.io',
    nativeCurrency: {
      name: 'Ethereum',
      symbol: 'ETH',
      decimals: 18,
    },
    color: '#8C8DFC',
    icon: '⚡',
    logoUrl: '/crypto-zksync.png',
  },
  linea: {
    id: 59144,
    name: 'Linea',
    shortName: 'Linea',
    rpcUrl: 'https://rpc.linea.build',
    explorerUrl: 'https://lineascan.build',
    nativeCurrency: {
      name: 'Ethereum',
      symbol: 'ETH',
      decimals: 18,
    },
    color: '#121212',
    icon: '📐',
    logoUrl: '/crypto-linea.png',
  },
  bitcoin: {
    id: 0,
    name: 'Bitcoin',
    shortName: 'BTC',
    rpcUrl: 'https://blockstream.info/api', // Blockstream API
    explorerUrl: 'https://blockstream.info',
    nativeCurrency: {
      name: 'Bitcoin',
      symbol: 'BTC',
      decimals: 8,
    },
    color: '#F7931A',
    icon: '₿',
    logoUrl: '/crypto-bitcoin.png',
  },
  litecoin: {
    id: 2,
    name: 'Litecoin',
    shortName: 'LTC',
    rpcUrl: 'https://api.blockcypher.com/v1/ltc/main',
    explorerUrl: 'https://blockchair.com/litecoin',
    nativeCurrency: {
      name: 'Litecoin',
      symbol: 'LTC',
      decimals: 8,
    },
    color: '#345D9D',
    icon: 'Ł',
    logoUrl: '/crypto-litecoin.png',
  },
  dogecoin: {
    id: 3,
    name: 'Dogecoin',
    shortName: 'DOGE',
    rpcUrl: 'https://api.blockcypher.com/v1/doge/main',
    explorerUrl: 'https://blockchair.com/dogecoin',
    nativeCurrency: {
      name: 'Dogecoin',
      symbol: 'DOGE',
      decimals: 8,
    },
    color: '#C3A634',
    icon: '🐕',
    logoUrl: '/crypto-doge.png',
  },
  bitcoincash: {
    id: 145,
    name: 'Bitcoin Cash',
    shortName: 'BCH',
    rpcUrl: 'https://api.blockcypher.com/v1/bcy/test',
    explorerUrl: 'https://blockchair.com/bitcoin-cash',
    nativeCurrency: {
      name: 'Bitcoin Cash',
      symbol: 'BCH',
      decimals: 8,
    },
    color: '#8DC351',
    icon: '💵',
    logoUrl: '/crypto-bitcoincash.png',
  },
};

export const DEFAULT_CHAIN = 'ethereum';

export const POPULAR_TOKENS: Record<string, any[]> = {
  ethereum: [
    {
      address: '0xdAC17F958D2ee523a2206206994597C13D831ec7',
      symbol: 'USDT',
      name: 'Tether USD',
      decimals: 6,
      logo: '/crypto-usdt.png',
    },
    {
      address: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
      symbol: 'USDC',
      name: 'USD Coin',
      decimals: 6,
      logo: '/crypto-usdc.png',
    },
    {
      address: '0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599',
      symbol: 'WBTC',
      name: 'Wrapped Bitcoin',
      decimals: 8,
      logo: '/crypto-wbtc.png',
    },
    {
      address: '0x514910771AF9Ca656af840dff83E8264EcF986CA',
      symbol: 'LINK',
      name: 'Chainlink',
      decimals: 18,
      logo: '/crypto-link.png',
    },
  ],
  polygon: [
    {
      address: '0xc2132D05D31c914a87C6611C10748AEb04B58e8F',
      symbol: 'USDT',
      name: 'Tether USD',
      decimals: 6,
      logo: '/crypto-usdt.png',
    },
    {
      address: '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174',
      symbol: 'USDC',
      name: 'USD Coin',
      decimals: 6,
      logo: '/crypto-usdc.png',
    },
  ],
  arbitrum: [
    {
      address: '0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9',
      symbol: 'USDT',
      name: 'Tether USD',
      decimals: 6,
      logo: '/crypto-usdt.png',
    },
    {
      address: '0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8',
      symbol: 'USDC',
      name: 'USD Coin',
      decimals: 6,
      logo: '/crypto-usdc.png',
    },
  ],
  base: [
    {
      address: '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913',
      symbol: 'USDC',
      name: 'USD Coin',
      decimals: 6,
      logo: '/crypto-usdc.png',
    },
  ],
  bsc: [
    {
      address: '0x55d398326f99059fF775485246999027B3197955',
      symbol: 'USDT',
      name: 'Tether USD',
      decimals: 18,
      logo: '/crypto-usdt.png',
    },
    {
      address: '0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d',
      symbol: 'USDC',
      name: 'USD Coin',
      decimals: 18,
      logo: '/crypto-usdc.png',
    },
    {
      address: '0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56',
      symbol: 'BUSD',
      name: 'Binance USD',
      decimals: 18,
      logo: '💰',
    },
  ],
  bscTestnet: [
    {
      address: '0x2C1421595151991ac3894943123d6c285bdF5116',
      symbol: 'BLAZE',
      name: 'Blaze Token',
      decimals: 18,
      logo: '🔥',
    },
  ],
  optimism: [
    {
      address: '0x94b008aA00579c1307B0EF2c499aD98a8ce58e58',
      symbol: 'USDT',
      name: 'Tether USD',
      decimals: 6,
      logo: '/crypto-usdt.png',
    },
    {
      address: '0x7F5c764cBc14f9669B88837ca1490cCa17c31607',
      symbol: 'USDC',
      name: 'USD Coin',
      decimals: 6,
      logo: '/crypto-usdc.png',
    },
  ],
  avalanche: [
    {
      address: '0x9702230A8Ea53601f5cD2dc00fDBc13d4dF4A8c7',
      symbol: 'USDT',
      name: 'Tether USD',
      decimals: 6,
      logo: '/crypto-usdt.png',
    },
    {
      address: '0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E',
      symbol: 'USDC',
      name: 'USD Coin',
      decimals: 6,
      logo: '/crypto-usdc.png',
    },
  ],
  fantom: [
    {
      address: '0x049d68029688eAbF473097a2fC38ef61633A3C7A',
      symbol: 'USDT',
      name: 'Tether USD',
      decimals: 6,
      logo: '/crypto-usdt.png',
    },
    {
      address: '0x04068DA6C83AFCFA0e13ba15A6696662335D5B75',
      symbol: 'USDC',
      name: 'USD Coin',
      decimals: 6,
      logo: '/crypto-usdc.png',
    },
  ],
  cronos: [
    {
      address: '0x66e428c3f67a68878562e79A0234c1F83c208770',
      symbol: 'USDT',
      name: 'Tether USD',
      decimals: 6,
      logo: '/crypto-usdt.png',
    },
    {
      address: '0xc21223249CA28397B4B6541dfFaEcC539BfF0c59',
      symbol: 'USDC',
      name: 'USD Coin',
      decimals: 6,
      logo: '/crypto-usdc.png',
    },
  ],
  zksync: [
    {
      address: '0x493257fD37EDB34451f62EDf8D2a0C418852bA4C',
      symbol: 'USDT',
      name: 'Tether USD',
      decimals: 6,
      logo: '/crypto-usdt.png',
    },
    {
      address: '0x3355df6D4c9C3035724Fd0e3914dE96A5a83aaf4',
      symbol: 'USDC',
      name: 'USD Coin',
      decimals: 6,
      logo: '/crypto-usdc.png',
    },
  ],
  linea: [
    {
      address: '0xA219439258ca9da29E9Cc4cE5596924745e12B93',
      symbol: 'USDT',
      name: 'Tether USD',
      decimals: 6,
      logo: '/crypto-usdt.png',
    },
    {
      address: '0x176211869cA2b568f2A7D4EE941E073a821EE1ff',
      symbol: 'USDC',
      name: 'USD Coin',
      decimals: 6,
      logo: '/crypto-usdc.png',
    },
  ],
  // Solana SPL Tokens - fetched dynamically via SolanaService.getSPLTokenBalances()
  // Note: These are just for reference, actual SPL tokens are loaded from chain
  solana: [
    {
      address: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
      symbol: 'USDC',
      name: 'USD Coin',
      decimals: 6,
      logo: '/crypto-usdc.png',
    },
    {
      address: 'Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB',
      symbol: 'USDT',
      name: 'Tether USD',
      decimals: 6,
      logo: '/crypto-usdt.png',
    },
    {
      address: '4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R',
      symbol: 'RAY',
      name: 'Raydium',
      decimals: 6,
      logo: '🌊',
    },
    {
      address: 'DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263',
      symbol: 'BONK',
      name: 'Bonk',
      decimals: 5,
      logo: '🐶',
    },
  ],
};






